name: scott robertson design
favicon: null
layout_spectrum: 0.20023491908796132
typography_spectrum: 0.10998
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d3112b'
    - '#e77887'
    - '#cfc2af'
    - '#5b0000'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.9375
  rhythmicContrast: 0.75
purpose: []
